@BigaiRestaurantsApiHostAddress = http://localhost:7000

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants
Accept: application/json

###

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants/1
Accept: application/json

###
