@BigaiRestaurantsApiHostAddress = http://localhost:7000
@restaurantId = 123

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants
Accept: application/json

###

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants/1
Accept: application/json

###

DELETE {{BigaiRestaurantsApiHostAddress}}/api/restaurants/4
Accept: application/json

###

POST {{BigaiRestaurantsApiHostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Spicy Delights",
    "Description": "A culinary experience like no other",
    "Category": "Fine Dining",
    "HasDelivery": true,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "54321"
}

###

PATCH  {{BigaiRestaurantsApiHostAddress}}/api/restaurants/2
Content-Type: application/json

{
    "Name": "Spicy Delights",
    "Description": "A culinary experience like no other",
    "HasDelivery": false
}

###

POST {{BigaiRestaurantsApiHostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
    "Name": "Spaguetti Bolognese",
    "Description": "Classic Italian pasta dish with rich meat sauce",
    "Price": 28.59,
    "KiloCalories": 7
}
