@BigaiRestaurantsApiHostAddress = http://localhost:7000
@restaurantId = 123
@dishId = 3
@token = CfDJ8EHapphEpXVCqJfhjTkQvYnYuPh9FW1rSu_DfPzLDuSKwU5r7YqkUOGe73XbqLNT8PZXizRBFCm3YASS3Do6MxO3_jwXMRzLyuXTLgmX61t8DgxbIroL8_vixDmM4clri1MxixB34ROUjr6_O9ZJgRt4n3LzWS0xNREkciZ8e8zYuzz3VAOAcNZj1juHofWIopVZYZwj8GjFJ9n-29f_5hg9p_puo0mqVr4_Lqy942EFtJdq2HKhyHJaT27ugDMwyKjQK8cU-mg1VebuAJlmBwSf00MjVUgRRvEtJq8KG_CMbSwQ-kXOK1wNL3mxvA3awiZrnyGRixIPF3km61YkwQHpQTEDGcweqBnUw2uP1LFxP5HwM4XoQXAFwYBbrEtj-szw49t1DRpwtdwexFnSfU5quxdRiEFgj-3fHwf4nQ7z9VnPqxOjrC71z5twy87W_SF39IGxiSx1I6s8qeHAgT791YQUmpVLnNtfwnvh1fXuhlxTPuokRpPbxgHuv_9GBG8OoI19rP1-QwQaTaF_b97sEEGLiAUPdWMKtHB56sD-OKaB_g7kLmCaBhtMHsKWuAcT0-GDGsGPfuzrI2_LMJrJ-D-iwDCJnC0JhwaiudcDSQzUrsM3U6-723nFyat7VRm3Ixz6LPaYiPdv7kvQM_VHvx_ApB0n_D3C4prnLWmNU_VvRAUg5FmgbxFWtvrZTw

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants
Accept: application/json
Authorization: Bearer {{token}}
###

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants/1
Accept: application/json

###

DELETE {{BigaiRestaurantsApiHostAddress}}/api/restaurants/4
Accept: application/json

###

POST {{BigaiRestaurantsApiHostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Spicy Delights",
    "Description": "A culinary experience like no other",
    "Category": "Fine Dining",
    "HasDelivery": true,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "54321"
}

###

PATCH  {{BigaiRestaurantsApiHostAddress}}/api/restaurants/2
Content-Type: application/json

{
    "Name": "Spicy Delights",
    "Description": "A culinary experience like no other",
    "HasDelivery": false
}

###

POST {{BigaiRestaurantsApiHostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
    "Name": "Spaguetti Bolognese",
    "Description": "Classic Italian pasta dish with rich meat sauce",
    "Price": 28.59,
    "KiloCalories": 7
}

###

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

###

GET {{BigaiRestaurantsApiHostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}
Content-Type: application/json

###

DELETE {{BigaiRestaurantsApiHostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json


###

POST {{BigaiRestaurantsApiHostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Passw0rd!"
}

###

POST {{BigaiRestaurantsApiHostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Passw0rd!"
}